const express = require("express");
const {v4: uuidV4} = require ("uuid");

const app = express();
const customers = [];

app.use(express.json())

/**
 * CPF - String             -> Received by client post
 * Name - String            -> Received by client post
 * ID - uuid                -> Generated by the application
 * Statement - array[]      -> Generated by the application
 */
app.post("/account", (request, response)=>{
    const {cpf, name} = request.body;

    const customersAlreadyExists = customers.some(
        (customer)=> customer.cpf === cpf
    );

    if(customersAlreadyExists){
        return response.status(400).json({error: "Customer Already Exists!"});
    }

    customers.push({
        cpf,
        name,
        id: uuidV4(),
        statement: []
    });

    console.debug(customers);

    return response.status(201).end();
})

app.get("/statement/:cpf", (request, response)=>{
    const {cpf} = request.params;
    const customer = customers.find(customer => customer.cpf === cpf);
    
    if(!customer){
        return response.status(400).json({error: "Customer Not Found!"})
    }

    console.debug(customer.statement);

    return response.json(customer.statement)
})

app.get("/statement", (request, response)=>{
    const {cpf} = request.headers;
    const customer = customers.find(customer => customer.cpf === cpf);
    
    if(!customer){
        return response.status(400).json({error: "Customer Not Found!"})
    }

    console.debug(customer.statement);

    return response.json(customer.statement)
})

app.listen(8332);